// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LogSearchesColumns holds the columns for the "log_searches" table.
	LogSearchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "keyword", Type: field.TypeString},
		{Name: "page", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LogSearchesTable holds the schema information for the "log_searches" table.
	LogSearchesTable = &schema.Table{
		Name:       "log_searches",
		Columns:    LogSearchesColumns,
		PrimaryKey: []*schema.Column{LogSearchesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LogSearchesTable,
	}
)

func init() {
}
