// Code generated by entc, DO NOT EDIT.

package logsearch

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/RiskyFeryansyahP/bibit-movies/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Keyword applies equality check predicate on the "keyword" field. It's identical to KeywordEQ.
func Keyword(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKeyword), v))
	})
}

// Page applies equality check predicate on the "page" field. It's identical to PageEQ.
func Page(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPage), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// KeywordEQ applies the EQ predicate on the "keyword" field.
func KeywordEQ(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKeyword), v))
	})
}

// KeywordNEQ applies the NEQ predicate on the "keyword" field.
func KeywordNEQ(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldKeyword), v))
	})
}

// KeywordIn applies the In predicate on the "keyword" field.
func KeywordIn(vs ...string) predicate.LogSearch {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldKeyword), v...))
	})
}

// KeywordNotIn applies the NotIn predicate on the "keyword" field.
func KeywordNotIn(vs ...string) predicate.LogSearch {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldKeyword), v...))
	})
}

// KeywordGT applies the GT predicate on the "keyword" field.
func KeywordGT(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldKeyword), v))
	})
}

// KeywordGTE applies the GTE predicate on the "keyword" field.
func KeywordGTE(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldKeyword), v))
	})
}

// KeywordLT applies the LT predicate on the "keyword" field.
func KeywordLT(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldKeyword), v))
	})
}

// KeywordLTE applies the LTE predicate on the "keyword" field.
func KeywordLTE(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldKeyword), v))
	})
}

// KeywordContains applies the Contains predicate on the "keyword" field.
func KeywordContains(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldKeyword), v))
	})
}

// KeywordHasPrefix applies the HasPrefix predicate on the "keyword" field.
func KeywordHasPrefix(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldKeyword), v))
	})
}

// KeywordHasSuffix applies the HasSuffix predicate on the "keyword" field.
func KeywordHasSuffix(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldKeyword), v))
	})
}

// KeywordEqualFold applies the EqualFold predicate on the "keyword" field.
func KeywordEqualFold(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldKeyword), v))
	})
}

// KeywordContainsFold applies the ContainsFold predicate on the "keyword" field.
func KeywordContainsFold(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldKeyword), v))
	})
}

// PageEQ applies the EQ predicate on the "page" field.
func PageEQ(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPage), v))
	})
}

// PageNEQ applies the NEQ predicate on the "page" field.
func PageNEQ(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPage), v))
	})
}

// PageIn applies the In predicate on the "page" field.
func PageIn(vs ...string) predicate.LogSearch {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPage), v...))
	})
}

// PageNotIn applies the NotIn predicate on the "page" field.
func PageNotIn(vs ...string) predicate.LogSearch {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPage), v...))
	})
}

// PageGT applies the GT predicate on the "page" field.
func PageGT(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPage), v))
	})
}

// PageGTE applies the GTE predicate on the "page" field.
func PageGTE(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPage), v))
	})
}

// PageLT applies the LT predicate on the "page" field.
func PageLT(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPage), v))
	})
}

// PageLTE applies the LTE predicate on the "page" field.
func PageLTE(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPage), v))
	})
}

// PageContains applies the Contains predicate on the "page" field.
func PageContains(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPage), v))
	})
}

// PageHasPrefix applies the HasPrefix predicate on the "page" field.
func PageHasPrefix(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPage), v))
	})
}

// PageHasSuffix applies the HasSuffix predicate on the "page" field.
func PageHasSuffix(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPage), v))
	})
}

// PageEqualFold applies the EqualFold predicate on the "page" field.
func PageEqualFold(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPage), v))
	})
}

// PageContainsFold applies the ContainsFold predicate on the "page" field.
func PageContainsFold(v string) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPage), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LogSearch {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LogSearch {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LogSearch(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LogSearch) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LogSearch) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LogSearch) predicate.LogSearch {
	return predicate.LogSearch(func(s *sql.Selector) {
		p(s.Not())
	})
}
