version: "3.9"
services:

  # postgres db
  postgres:
    image: postgres:13.3-alpine
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bibit