// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/RiskyFeryansyahP/bibit-movies/ent/logsearch"
)

// LogSearchCreate is the builder for creating a LogSearch entity.
type LogSearchCreate struct {
	config
	mutation *LogSearchMutation
	hooks    []Hook
}

// SetKeyword sets the "keyword" field.
func (lsc *LogSearchCreate) SetKeyword(s string) *LogSearchCreate {
	lsc.mutation.SetKeyword(s)
	return lsc
}

// SetPage sets the "page" field.
func (lsc *LogSearchCreate) SetPage(s string) *LogSearchCreate {
	lsc.mutation.SetPage(s)
	return lsc
}

// SetCreatedAt sets the "created_at" field.
func (lsc *LogSearchCreate) SetCreatedAt(t time.Time) *LogSearchCreate {
	lsc.mutation.SetCreatedAt(t)
	return lsc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lsc *LogSearchCreate) SetNillableCreatedAt(t *time.Time) *LogSearchCreate {
	if t != nil {
		lsc.SetCreatedAt(*t)
	}
	return lsc
}

// Mutation returns the LogSearchMutation object of the builder.
func (lsc *LogSearchCreate) Mutation() *LogSearchMutation {
	return lsc.mutation
}

// Save creates the LogSearch in the database.
func (lsc *LogSearchCreate) Save(ctx context.Context) (*LogSearch, error) {
	var (
		err  error
		node *LogSearch
	)
	lsc.defaults()
	if len(lsc.hooks) == 0 {
		if err = lsc.check(); err != nil {
			return nil, err
		}
		node, err = lsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LogSearchMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lsc.check(); err != nil {
				return nil, err
			}
			lsc.mutation = mutation
			if node, err = lsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(lsc.hooks) - 1; i >= 0; i-- {
			if lsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (lsc *LogSearchCreate) SaveX(ctx context.Context) *LogSearch {
	v, err := lsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lsc *LogSearchCreate) Exec(ctx context.Context) error {
	_, err := lsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lsc *LogSearchCreate) ExecX(ctx context.Context) {
	if err := lsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lsc *LogSearchCreate) defaults() {
	if _, ok := lsc.mutation.CreatedAt(); !ok {
		v := logsearch.DefaultCreatedAt()
		lsc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lsc *LogSearchCreate) check() error {
	if _, ok := lsc.mutation.Keyword(); !ok {
		return &ValidationError{Name: "keyword", err: errors.New(`ent: missing required field "keyword"`)}
	}
	if _, ok := lsc.mutation.Page(); !ok {
		return &ValidationError{Name: "page", err: errors.New(`ent: missing required field "page"`)}
	}
	if _, ok := lsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	return nil
}

func (lsc *LogSearchCreate) sqlSave(ctx context.Context) (*LogSearch, error) {
	_node, _spec := lsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (lsc *LogSearchCreate) createSpec() (*LogSearch, *sqlgraph.CreateSpec) {
	var (
		_node = &LogSearch{config: lsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: logsearch.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: logsearch.FieldID,
			},
		}
	)
	if value, ok := lsc.mutation.Keyword(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: logsearch.FieldKeyword,
		})
		_node.Keyword = value
	}
	if value, ok := lsc.mutation.Page(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: logsearch.FieldPage,
		})
		_node.Page = value
	}
	if value, ok := lsc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: logsearch.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	return _node, _spec
}

// LogSearchCreateBulk is the builder for creating many LogSearch entities in bulk.
type LogSearchCreateBulk struct {
	config
	builders []*LogSearchCreate
}

// Save creates the LogSearch entities in the database.
func (lscb *LogSearchCreateBulk) Save(ctx context.Context) ([]*LogSearch, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lscb.builders))
	nodes := make([]*LogSearch, len(lscb.builders))
	mutators := make([]Mutator, len(lscb.builders))
	for i := range lscb.builders {
		func(i int, root context.Context) {
			builder := lscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LogSearchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lscb *LogSearchCreateBulk) SaveX(ctx context.Context) []*LogSearch {
	v, err := lscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lscb *LogSearchCreateBulk) Exec(ctx context.Context) error {
	_, err := lscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lscb *LogSearchCreateBulk) ExecX(ctx context.Context) {
	if err := lscb.Exec(ctx); err != nil {
		panic(err)
	}
}
