// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/RiskyFeryansyahP/bibit-movies/ent/logsearch"
	"github.com/RiskyFeryansyahP/bibit-movies/ent/predicate"
)

// LogSearchDelete is the builder for deleting a LogSearch entity.
type LogSearchDelete struct {
	config
	hooks    []Hook
	mutation *LogSearchMutation
}

// Where appends a list predicates to the LogSearchDelete builder.
func (lsd *LogSearchDelete) Where(ps ...predicate.LogSearch) *LogSearchDelete {
	lsd.mutation.Where(ps...)
	return lsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lsd *LogSearchDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lsd.hooks) == 0 {
		affected, err = lsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LogSearchMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lsd.mutation = mutation
			affected, err = lsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lsd.hooks) - 1; i >= 0; i-- {
			if lsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lsd *LogSearchDelete) ExecX(ctx context.Context) int {
	n, err := lsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lsd *LogSearchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: logsearch.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: logsearch.FieldID,
			},
		},
	}
	if ps := lsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lsd.driver, _spec)
}

// LogSearchDeleteOne is the builder for deleting a single LogSearch entity.
type LogSearchDeleteOne struct {
	lsd *LogSearchDelete
}

// Exec executes the deletion query.
func (lsdo *LogSearchDeleteOne) Exec(ctx context.Context) error {
	n, err := lsdo.lsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{logsearch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lsdo *LogSearchDeleteOne) ExecX(ctx context.Context) {
	lsdo.lsd.ExecX(ctx)
}
