// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/RiskyFeryansyahP/bibit-movies/ent/logsearch"
	"github.com/RiskyFeryansyahP/bibit-movies/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	logsearchFields := schema.LogSearch{}.Fields()
	_ = logsearchFields
	// logsearchDescCreatedAt is the schema descriptor for created_at field.
	logsearchDescCreatedAt := logsearchFields[2].Descriptor()
	// logsearch.DefaultCreatedAt holds the default value on creation for the created_at field.
	logsearch.DefaultCreatedAt = logsearchDescCreatedAt.Default.(func() time.Time)
}
